-- PostgreSQL 16 + pgvector DDL for knowledge-base.
-- DDL is intentionally centralized in this file.

create extension if not exists vector;

create table if not exists t_user (
    id bigint generated by default as identity primary key,
    username varchar(128) not null,
    email varchar(255),
    phone varchar(32),
    display_name varchar(128) not null default '',
    avatar varchar(1024),
    password_hash varchar(255),
    external_subject varchar(255),
    status varchar(32) not null default 'active',
    last_login_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (username)
);

create unique index if not exists uk_t_user_email on t_user (email) where email is not null;

create unique index if not exists uk_t_user_external_subject on t_user (external_subject) where external_subject is not null;

create index if not exists idx_t_user_status on t_user (status);

create table if not exists t_login_log (
    id bigint generated by default as identity primary key,
    user_id bigint,
    login_account varchar(255) not null,
    login_type varchar(32) not null,
    result varchar(32) not null,
    failure_reason varchar(64),
    ip_address varchar(64),
    user_agent varchar(1024),
    request_id varchar(128),
    created_at timestamptz not null default now()
);

create index if not exists idx_t_login_log_user_created on t_login_log (user_id, created_at);

create index if not exists idx_t_login_log_account_created on t_login_log (login_account, created_at);

create index if not exists idx_t_login_log_result_created on t_login_log (result, created_at);

create table if not exists t_auth_session (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    tenant_id bigint not null,
    jti varchar(64) not null unique,
    token_type varchar(32) not null,
    expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null default now()
);

alter table t_auth_session add column if not exists tenant_id bigint;

create index if not exists idx_t_auth_session_user_id on t_auth_session (user_id);

create index if not exists idx_t_auth_session_active on t_auth_session (jti, revoked_at, expires_at);

create table if not exists t_platform_role (
    id bigint generated by default as identity primary key,
    code varchar(64) not null,
    name varchar(128) not null,
    description varchar(500) not null default '',
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (code)
);

create index if not exists idx_t_platform_role_status on t_platform_role (status);

create table if not exists t_platform_user_role (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    role_id bigint not null,
    created_at timestamptz not null default now(),
    created_by bigint,
    unique (user_id, role_id)
);

create index if not exists idx_t_platform_user_role_user_id on t_platform_user_role (user_id);

create index if not exists idx_t_platform_user_role_role_id on t_platform_user_role (role_id);

create table if not exists t_system_menu (
    id bigint generated by default as identity primary key,
    parent_id bigint,
    code varchar(100) not null,
    name varchar(100) not null,
    menu_type varchar(32) not null,
    route_path varchar(255),
    icon varchar(100),
    sort_order integer not null default 0,
    visible boolean not null default true,
    status varchar(32) not null default 'active',
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (menu_type in ('directory', 'item'))
);

create unique index if not exists uk_t_system_menu_code on t_system_menu (code);

create index if not exists idx_t_system_menu_parent_sort on t_system_menu (parent_id, sort_order, id);

create index if not exists idx_t_system_menu_route_path on t_system_menu (route_path);

create index if not exists idx_t_system_menu_status_visible on t_system_menu (status, visible);

comment on table t_system_menu is '系统菜单表，只保存导航目录和菜单项，不保存页面按钮或接口权限';
comment on column t_system_menu.id is '系统菜单主键';
comment on column t_system_menu.parent_id is '父菜单主键，顶级菜单为空';
comment on column t_system_menu.code is '菜单编码，全局唯一';
comment on column t_system_menu.name is '菜单名称';
comment on column t_system_menu.menu_type is '菜单类型：directory 目录，item 菜单项';
comment on column t_system_menu.route_path is '菜单跳转路径，目录为空';
comment on column t_system_menu.icon is '菜单图标标识';
comment on column t_system_menu.sort_order is '同级菜单排序值，值越小越靠前';
comment on column t_system_menu.visible is '是否显示在导航菜单中';
comment on column t_system_menu.status is '菜单状态：active 启用，disabled 禁用';
comment on column t_system_menu.meta is '菜单扩展元数据';
comment on column t_system_menu.created_at is '创建时间';
comment on column t_system_menu.updated_at is '更新时间';
comment on index uk_t_system_menu_code is '菜单编码唯一索引';
comment on index idx_t_system_menu_parent_sort is '按父菜单和排序值查询菜单树';
comment on index idx_t_system_menu_route_path is '按菜单跳转路径查询';
comment on index idx_t_system_menu_status_visible is '按菜单状态和显示标记查询';

create table if not exists t_role_menu (
    id bigint generated by default as identity primary key,
    role_scope varchar(32) not null,
    role_code varchar(64) not null,
    menu_id bigint not null,
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    created_by bigint,
    updated_at timestamptz not null default now(),
    check (role_scope in ('platform', 'tenant', 'organization'))
);

create unique index if not exists uk_t_role_menu_role_menu on t_role_menu (role_scope, role_code, menu_id);

create index if not exists idx_t_role_menu_role on t_role_menu (role_scope, role_code, status);

create index if not exists idx_t_role_menu_menu on t_role_menu (menu_id, status);

comment on table t_role_menu is '角色菜单关系表，保存角色可展示的系统菜单';
comment on column t_role_menu.id is '角色菜单关系主键';
comment on column t_role_menu.role_scope is '角色作用域：platform 平台，tenant 租户，organization 组织';
comment on column t_role_menu.role_code is '角色编码，由对应角色域校验';
comment on column t_role_menu.menu_id is '系统菜单主键';
comment on column t_role_menu.status is '关系状态：active 启用，disabled 禁用';
comment on column t_role_menu.created_at is '创建时间';
comment on column t_role_menu.created_by is '创建人用户主键';
comment on column t_role_menu.updated_at is '更新时间';
comment on index uk_t_role_menu_role_menu is '同一角色与同一菜单只能建立一条关系';
comment on index idx_t_role_menu_role is '按角色查询有效菜单';
comment on index idx_t_role_menu_menu is '按菜单查询有效角色';

create table if not exists t_system_menu_action (
    id bigint generated by default as identity primary key,
    menu_id bigint not null,
    code varchar(128) not null,
    name varchar(100) not null,
    action_type varchar(32) not null default 'business',
    sort_order integer not null default 0,
    status varchar(32) not null default 'active',
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (action_type in ('button', 'business'))
);

create unique index if not exists uk_t_system_menu_action_code on t_system_menu_action (code);

create unique index if not exists uk_t_system_menu_action_menu_name on t_system_menu_action (menu_id, name);

create index if not exists idx_t_system_menu_action_menu on t_system_menu_action (menu_id, status);

comment on table t_system_menu_action is '页面操作表，保存菜单页面下的按钮和业务操作';
comment on column t_system_menu_action.id is '页面操作主键';
comment on column t_system_menu_action.menu_id is '所属页面菜单主键，逻辑关联 t_system_menu.id';
comment on column t_system_menu_action.code is '操作编码，全局唯一';
comment on column t_system_menu_action.name is '操作名称';
comment on column t_system_menu_action.action_type is '操作类型：button 按钮，business 业务操作';
comment on column t_system_menu_action.sort_order is '页面内操作排序';
comment on column t_system_menu_action.status is '操作状态：active 启用，disabled 禁用';
comment on column t_system_menu_action.meta is '操作扩展元数据';
comment on column t_system_menu_action.created_at is '创建时间';
comment on column t_system_menu_action.updated_at is '更新时间';

create table if not exists t_role_menu_action (
    id bigint generated by default as identity primary key,
    role_scope varchar(32) not null,
    role_code varchar(64) not null,
    action_id bigint not null,
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    created_by bigint,
    updated_at timestamptz not null default now(),
    check (role_scope in ('platform', 'tenant', 'organization'))
);

create unique index if not exists uk_t_role_menu_action_role_action on t_role_menu_action (role_scope, role_code, action_id);

create index if not exists idx_t_role_menu_action_role on t_role_menu_action (role_scope, role_code, status);

create index if not exists idx_t_role_menu_action_action on t_role_menu_action (action_id, status);

comment on table t_role_menu_action is '角色页面操作授权表，保存角色对页面操作的授权';
comment on column t_role_menu_action.id is '角色页面操作授权主键';
comment on column t_role_menu_action.role_scope is '角色作用域：platform 平台，tenant 租户，organization 组织';
comment on column t_role_menu_action.role_code is '角色编码，由对应角色域校验';
comment on column t_role_menu_action.action_id is '页面操作主键，逻辑关联 t_system_menu_action.id';
comment on column t_role_menu_action.status is '授权状态：active 启用，disabled 禁用';
comment on column t_role_menu_action.created_at is '创建时间';
comment on column t_role_menu_action.created_by is '授权创建人用户主键';
comment on column t_role_menu_action.updated_at is '更新时间';

create table if not exists t_tenant (
    id bigint generated by default as identity primary key,
    code varchar(64) not null,
    name varchar(255) not null,
    logo varchar(1024),
    contact_name varchar(128),
    contact_email varchar(255),
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (code)
);

create index if not exists idx_t_tenant_status on t_tenant (status);

alter table t_tenant add column if not exists description varchar(500) not null default '';

create table if not exists t_tenant_member (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    user_id bigint not null,
    role_code varchar(64) not null,
    is_primary boolean not null default false,
    status varchar(32) not null default 'active',
    joined_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tenant_id, user_id)
);

create index if not exists idx_t_tenant_member_tenant_status on t_tenant_member (tenant_id, status);

create index if not exists idx_t_tenant_member_user_id on t_tenant_member (user_id);

create index if not exists idx_t_tenant_member_tenant_role on t_tenant_member (tenant_id, role_code);

create unique index if not exists uk_t_tenant_member_active_owner on t_tenant_member (tenant_id) where role_code = 'tenant_owner' and status = 'active';

create table if not exists t_organization (
    id bigint generated by default as identity primary key,
    tenant_id bigint,
    parent_id bigint,
    code varchar(64) not null,
    name varchar(255) not null,
    leader_user_id bigint,
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tenant_id, code),
    unique (tenant_id, id)
);

create index if not exists idx_t_organization_tenant_parent on t_organization (tenant_id, parent_id);

create index if not exists idx_t_organization_tenant_status on t_organization (tenant_id, status);

alter table t_organization alter column tenant_id drop not null;

create table if not exists t_organization_member (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    user_id bigint not null,
    role_code varchar(64) not null,
    is_primary boolean not null default false,
    status varchar(32) not null default 'active',
    joined_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (organization_id, user_id)
);

create index if not exists idx_t_organization_member_organization_status on t_organization_member (organization_id, status);

create index if not exists idx_t_organization_member_user_id on t_organization_member (user_id);

create table if not exists t_knowledge_base (
    id bigint generated by default as identity primary key,
    tenant_id bigint,
    name varchar(255) not null,
    description varchar(500) not null default '',
    owner_id varchar(128) not null,
    visibility varchar(32) not null,
    embedding_model varchar(128) not null,
    chunk_size integer not null,
    chunk_overlap integer not null,
    retrieval_top_k integer not null,
    active_index_version_id bigint,
    system_prompt text not null default '',
    system_prompt_version integer not null default 1,
    system_prompt_updated_at timestamptz not null default now(),
    created_by bigint not null,
    status varchar(32) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_knowledge_base_owner_id on t_knowledge_base (owner_id);

create index if not exists idx_t_knowledge_base_status on t_knowledge_base (status);

alter table t_knowledge_base add column if not exists system_prompt text not null default '';
alter table t_knowledge_base add column if not exists system_prompt_version integer not null default 1;
alter table t_knowledge_base add column if not exists system_prompt_updated_at timestamptz not null default now();
alter table t_knowledge_base add column if not exists tenant_id bigint;
alter table t_knowledge_base add column if not exists created_by bigint;

-- Existing databases must backfill tenant_id and created_by before these columns can be made mandatory.
alter table t_knowledge_base alter column tenant_id drop not null;
alter table t_knowledge_base alter column created_by set not null;

create index if not exists idx_t_knowledge_base_tenant_id on t_knowledge_base (tenant_id);

create table if not exists t_knowledge_base_organization (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    organization_id bigint not null,
    created_by bigint not null,
    created_at timestamptz not null default now(),
    unique (kb_id, organization_id)
);

create index if not exists idx_t_knowledge_base_organization_kb_id on t_knowledge_base_organization (kb_id);
create index if not exists idx_t_knowledge_base_organization_org_id on t_knowledge_base_organization (organization_id);

create table if not exists t_knowledge_base_user (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    user_id bigint not null,
    created_by bigint not null,
    created_at timestamptz not null default now(),
    unique (kb_id, user_id)
);

create index if not exists idx_t_knowledge_base_user_kb_id on t_knowledge_base_user (kb_id);
create index if not exists idx_t_knowledge_base_user_user_id on t_knowledge_base_user (user_id);

create table if not exists t_knowledge_base_prompt (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    version integer not null,
    system_prompt text not null,
    created_by varchar(128) not null,
    created_at timestamptz not null default now(),
    unique (kb_id, version)
);

create index if not exists idx_t_knowledge_base_prompt_kb_version on t_knowledge_base_prompt (kb_id, version);

create table if not exists t_knowledge_base_qa_config_version (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    version_no integer not null,
    status varchar(20) not null,
    config_json jsonb not null default '{}'::jsonb,
    change_summary_json jsonb not null default '{}'::jsonb,
    requires_reindex boolean not null default false,
    affected_document_count integer not null default 0,
    created_by bigint not null,
    published_by bigint,
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (kb_id, version_no)
);

create unique index if not exists uq_t_knowledge_base_qa_config_draft on t_knowledge_base_qa_config_version (kb_id) where status = 'draft';
create unique index if not exists uq_t_knowledge_base_qa_config_published on t_knowledge_base_qa_config_version (kb_id) where status = 'published';
create index if not exists idx_t_knowledge_base_qa_config_kb_status on t_knowledge_base_qa_config_version (kb_id, status);

create table if not exists t_knowledge_base_qa_config_audit (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    config_version_id bigint,
    action varchar(32) not null,
    actor_id bigint not null,
    before_json jsonb not null default '{}'::jsonb,
    after_json jsonb not null default '{}'::jsonb,
    result varchar(20) not null,
    error_message text,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_knowledge_base_qa_config_audit_kb_created on t_knowledge_base_qa_config_audit (kb_id, created_at);

create table if not exists t_knowledge_base_index_version (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    generation varchar(64) not null,
    config_version_id bigint,
    status varchar(20) not null,
    vector_collection varchar(255) not null,
    created_at timestamptz not null default now(),
    activated_at timestamptz,
    retired_at timestamptz,
    unique (kb_id, generation)
);

create unique index if not exists uq_t_knowledge_base_index_active on t_knowledge_base_index_version (kb_id) where status = 'active';
create index if not exists idx_t_knowledge_base_index_kb_status on t_knowledge_base_index_version (kb_id, status);

create table if not exists t_document (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    source_type varchar(32) not null,
    source_name varchar(512) not null,
    source_uri text,
    content_type varchar(128) not null,
    object_path varchar(1024) not null,
    file_size bigint not null default 0,
    content_hash varchar(128) not null,
    parser varchar(128),
    status varchar(32) not null,
    error_message text,
    created_by varchar(128) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_document_kb_status on t_document (kb_id, status);

create index if not exists idx_t_document_content_hash on t_document (content_hash);

create index if not exists idx_t_document_created_by on t_document (created_by);


create table if not exists t_document_chunk (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    document_id bigint not null,
    parent_id bigint,
    chunk_index integer not null,
    content text not null,
    content_hash varchar(128) not null,
    source_name varchar(512) not null,
    page integer,
    section varchar(512),
    start_index integer,
    token_count integer,
    metadata jsonb not null default '{}'::jsonb,
    embedding_model varchar(128) not null,
    embedding vector,
    index_version_id bigint,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_document_chunk_kb_doc on t_document_chunk (kb_id, document_id);

create index if not exists idx_t_document_chunk_kb_index on t_document_chunk (kb_id, chunk_index);

create index if not exists idx_t_document_chunk_content_hash on t_document_chunk (content_hash);

create index if not exists idx_t_document_chunk_metadata_gin on t_document_chunk using gin (metadata);
create index if not exists idx_t_document_chunk_kb_index_version on t_document_chunk (kb_id, index_version_id);

-- Create the vector index after the embedding dimension and distance metric are finalized.
-- Example for cosine distance with HNSW:
-- create index if not exists idx_t_document_chunk_embedding_hnsw on t_document_chunk using hnsw (embedding vector_cosine_ops);


create table if not exists t_indexing_task (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    kb_id bigint not null,
    config_version_id bigint,
    index_version_id bigint,
    task_type varchar(32) not null,
    status varchar(32) not null,
    attempts integer not null default 0,
    max_attempts integer not null default 3,
    error_message text,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_indexing_task_document_id on t_indexing_task (document_id);

create index if not exists idx_t_indexing_task_status on t_indexing_task (status);

create index if not exists idx_t_indexing_task_kb_status on t_indexing_task (kb_id, status);
create index if not exists idx_t_indexing_task_kb_index_version on t_indexing_task (kb_id, index_version_id);


create table if not exists t_conversation (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    user_id varchar(128) not null,
    qa_config_version_id bigint,
    index_version_id bigint,
    title varchar(255),
    status varchar(32) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_conversation_user_id on t_conversation (user_id);

create index if not exists idx_t_conversation_kb_user on t_conversation (kb_id, user_id);
create index if not exists idx_t_conversation_index_version on t_conversation (kb_id, index_version_id);


create table if not exists t_conversation_message (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    kb_id bigint not null,
    user_id varchar(128) not null,
    role varchar(32) not null,
    content text not null,
    metadata jsonb not null default '{}'::jsonb,
    qa_config_version_id bigint,
    index_version_id bigint,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_conversation_message_conversation_id on t_conversation_message (conversation_id);

create index if not exists idx_t_conversation_message_kb_user on t_conversation_message (kb_id, user_id);

create index if not exists idx_t_conversation_message_created_at on t_conversation_message (created_at);
create index if not exists idx_t_conversation_message_index_version on t_conversation_message (kb_id, index_version_id);


create table if not exists t_message_citation (
    id bigint generated by default as identity primary key,
    message_id bigint not null,
    kb_id bigint not null,
    document_id bigint not null,
    chunk_id bigint not null,
    source_name varchar(512) not null,
    page integer,
    snippet text not null,
    score numeric(8, 6),
    rank integer not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_message_citation_message_id on t_message_citation (message_id);

create index if not exists idx_t_message_citation_document_id on t_message_citation (document_id);

create index if not exists idx_t_message_citation_chunk_id on t_message_citation (chunk_id);


create table if not exists t_evaluation_feedback (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    conversation_id bigint,
    message_id bigint,
    question text not null,
    expected_answer text,
    actual_answer text,
    expected_sources jsonb not null default '[]'::jsonb,
    rating integer,
    labels jsonb not null default '[]'::jsonb,
    comment text,
    created_by varchar(128) not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_evaluation_feedback_kb_created on t_evaluation_feedback (kb_id, created_at);

create index if not exists idx_t_evaluation_feedback_message_id on t_evaluation_feedback (message_id);


create table if not exists t_audit_log (
    id bigint generated by default as identity primary key,
    actor_id varchar(128) not null,
    action varchar(128) not null,
    action_cn varchar(128) not null,
    target_type varchar(64) not null,
    target_id varchar(128),
    request_id varchar(128),
    request_summary jsonb not null default '{}'::jsonb,
    result varchar(32) not null,
    error_message text,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_audit_log_actor_id on t_audit_log (actor_id);

create index if not exists idx_t_audit_log_target on t_audit_log (target_type, target_id);

create index if not exists idx_t_audit_log_created_at on t_audit_log (created_at);

create table if not exists t_evaluation_task (
    id bigint generated by default as identity primary key,
    name varchar(255) not null, kb_id bigint not null, config jsonb not null default '{}'::jsonb,
    status varchar(32) not null default 'active', created_by varchar(128) not null,
    created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_t_evaluation_task_status on t_evaluation_task (status);
create index if not exists idx_t_evaluation_task_kb on t_evaluation_task (kb_id, status);

create table if not exists t_evaluation_run (
    id bigint generated by default as identity primary key, task_id bigint not null, run_no integer not null,
    status varchar(32) not null, conclusion varchar(32), config_snapshot jsonb not null default '{}'::jsonb,
    metrics jsonb not null default '{}'::jsonb, report jsonb not null default '{}'::jsonb,
    question_count integer not null default 0, started_at timestamptz, finished_at timestamptz,
    created_at timestamptz not null default now(), unique (task_id, run_no)
);
create index if not exists idx_t_evaluation_run_task_status on t_evaluation_run (task_id, status);

create table if not exists t_evaluation_case_result (
    id bigint generated by default as identity primary key, run_id bigint not null, case_no integer not null,
    question text not null, question_source varchar(32) not null, question_basis varchar(64), answer text,
    status varchar(32) not null, termination_reason varchar(128), citation_count integer not null default 0,
    hit_count integer not null default 0, duration_ms integer not null default 0, error_code varchar(64),
    error_message text, metadata jsonb not null default '{}'::jsonb, unique (run_id, case_no)
);
create index if not exists idx_t_evaluation_case_result_run on t_evaluation_case_result (run_id, case_no);

create table if not exists t_evaluation_optimization (
    id bigint generated by default as identity primary key, run_id bigint not null, suggestion text not null,
    evidence jsonb not null default '{}'::jsonb, candidate_config jsonb not null default '{}'::jsonb,
    status varchar(32) not null default 'suggested', retest_run_id bigint, before_metrics jsonb,
    after_metrics jsonb, requires_confirmation boolean not null default true, created_by varchar(128) not null,
    created_at timestamptz not null default now()
);
create index if not exists idx_t_evaluation_optimization_run on t_evaluation_optimization (run_id, status);
