-- PostgreSQL 16 + pgvector DDL for knowledge-base.
-- DDL is intentionally centralized in this file.

create extension if not exists vector;

create table if not exists t_knowledge_base (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(500) not null default '',
    owner_id varchar(128) not null,
    visibility varchar(32) not null,
    embedding_model varchar(128) not null,
    chunk_size integer not null,
    chunk_overlap integer not null,
    retrieval_top_k integer not null,
    system_prompt text not null default '',
    system_prompt_version integer not null default 1,
    system_prompt_updated_at timestamptz not null default now(),
    status varchar(32) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_knowledge_base_owner_id on t_knowledge_base (owner_id);

create index if not exists idx_t_knowledge_base_status on t_knowledge_base (status);

alter table t_knowledge_base add column if not exists system_prompt text not null default '';
alter table t_knowledge_base add column if not exists system_prompt_version integer not null default 1;
alter table t_knowledge_base add column if not exists system_prompt_updated_at timestamptz not null default now();

create table if not exists t_knowledge_base_prompt (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    version integer not null,
    system_prompt text not null,
    created_by varchar(128) not null,
    created_at timestamptz not null default now(),
    unique (kb_id, version)
);

create index if not exists idx_t_knowledge_base_prompt_kb_version on t_knowledge_base_prompt (kb_id, version);

create table if not exists t_document (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    source_type varchar(32) not null,
    source_name varchar(512) not null,
    source_uri text,
    content_type varchar(128) not null,
    object_path varchar(1024) not null,
    file_size bigint not null default 0,
    content_hash varchar(128) not null,
    parser varchar(128),
    status varchar(32) not null,
    error_message text,
    created_by varchar(128) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_document_kb_status on t_document (kb_id, status);

create index if not exists idx_t_document_content_hash on t_document (content_hash);

create index if not exists idx_t_document_created_by on t_document (created_by);


create table if not exists t_document_chunk (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    document_id bigint not null,
    parent_id bigint,
    chunk_index integer not null,
    content text not null,
    content_hash varchar(128) not null,
    source_name varchar(512) not null,
    page integer,
    section varchar(512),
    start_index integer,
    token_count integer,
    metadata jsonb not null default '{}'::jsonb,
    embedding_model varchar(128) not null,
    embedding vector,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_document_chunk_kb_doc on t_document_chunk (kb_id, document_id);

create index if not exists idx_t_document_chunk_kb_index on t_document_chunk (kb_id, chunk_index);

create index if not exists idx_t_document_chunk_content_hash on t_document_chunk (content_hash);

create index if not exists idx_t_document_chunk_metadata_gin on t_document_chunk using gin (metadata);

-- Create the vector index after the embedding dimension and distance metric are finalized.
-- Example for cosine distance with HNSW:
-- create index if not exists idx_t_document_chunk_embedding_hnsw on t_document_chunk using hnsw (embedding vector_cosine_ops);


create table if not exists t_indexing_task (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    kb_id bigint not null,
    task_type varchar(32) not null,
    status varchar(32) not null,
    attempts integer not null default 0,
    max_attempts integer not null default 3,
    error_message text,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_indexing_task_document_id on t_indexing_task (document_id);

create index if not exists idx_t_indexing_task_status on t_indexing_task (status);

create index if not exists idx_t_indexing_task_kb_status on t_indexing_task (kb_id, status);


create table if not exists t_conversation (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    user_id varchar(128) not null,
    title varchar(255),
    status varchar(32) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_conversation_user_id on t_conversation (user_id);

create index if not exists idx_t_conversation_kb_user on t_conversation (kb_id, user_id);


create table if not exists t_conversation_message (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    kb_id bigint not null,
    user_id varchar(128) not null,
    role varchar(32) not null,
    content text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_conversation_message_conversation_id on t_conversation_message (conversation_id);

create index if not exists idx_t_conversation_message_kb_user on t_conversation_message (kb_id, user_id);

create index if not exists idx_t_conversation_message_created_at on t_conversation_message (created_at);


create table if not exists t_message_citation (
    id bigint generated by default as identity primary key,
    message_id bigint not null,
    kb_id bigint not null,
    document_id bigint not null,
    chunk_id bigint not null,
    source_name varchar(512) not null,
    page integer,
    snippet text not null,
    score numeric(8, 6),
    rank integer not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_message_citation_message_id on t_message_citation (message_id);

create index if not exists idx_t_message_citation_document_id on t_message_citation (document_id);

create index if not exists idx_t_message_citation_chunk_id on t_message_citation (chunk_id);


create table if not exists t_evaluation_feedback (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    conversation_id bigint,
    message_id bigint,
    question text not null,
    expected_answer text,
    actual_answer text,
    expected_sources jsonb not null default '[]'::jsonb,
    rating integer,
    labels jsonb not null default '[]'::jsonb,
    comment text,
    created_by varchar(128) not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_evaluation_feedback_kb_created on t_evaluation_feedback (kb_id, created_at);

create index if not exists idx_t_evaluation_feedback_message_id on t_evaluation_feedback (message_id);


create table if not exists t_audit_log (
    id bigint generated by default as identity primary key,
    actor_id varchar(128) not null,
    action varchar(128) not null,
    target_type varchar(64) not null,
    target_id varchar(128),
    request_id varchar(128),
    request_summary jsonb not null default '{}'::jsonb,
    result varchar(32) not null,
    error_message text,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_audit_log_actor_id on t_audit_log (actor_id);

create index if not exists idx_t_audit_log_target on t_audit_log (target_type, target_id);

create index if not exists idx_t_audit_log_created_at on t_audit_log (created_at);
