-- PostgreSQL 16 + pgvector DDL for knowledge-base.
-- DDL is intentionally centralized in this file.

create extension if not exists vector;

create table if not exists t_user (
    id bigint generated by default as identity primary key,
    username varchar(128) not null,
    email varchar(255),
    phone varchar(32),
    display_name varchar(128) not null default '',
    avatar varchar(1024),
    password_hash varchar(255),
    external_subject varchar(255),
    status varchar(32) not null default 'active',
    last_login_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (username)
);

create unique index if not exists uk_t_user_email on t_user (email) where email is not null;

create unique index if not exists uk_t_user_external_subject on t_user (external_subject) where external_subject is not null;

create index if not exists idx_t_user_status on t_user (status);

create table if not exists t_login_log (
    id bigint generated by default as identity primary key,
    user_id bigint,
    login_account varchar(255) not null,
    login_type varchar(32) not null,
    result varchar(32) not null,
    failure_reason varchar(64),
    ip_address varchar(64),
    user_agent varchar(1024),
    request_id varchar(128),
    created_at timestamptz not null default now()
);

create index if not exists idx_t_login_log_user_created on t_login_log (user_id, created_at);

create index if not exists idx_t_login_log_account_created on t_login_log (login_account, created_at);

create index if not exists idx_t_login_log_result_created on t_login_log (result, created_at);

create table if not exists t_auth_session (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    tenant_id bigint not null,
    jti varchar(64) not null unique,
    token_type varchar(32) not null,
    expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null default now()
);

alter table t_auth_session add column if not exists tenant_id bigint;

create index if not exists idx_t_auth_session_user_id on t_auth_session (user_id);

create index if not exists idx_t_auth_session_active on t_auth_session (jti, revoked_at, expires_at);

create table if not exists t_platform_role (
    id bigint generated by default as identity primary key,
    code varchar(64) not null,
    name varchar(128) not null,
    description varchar(500) not null default '',
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (code)
);

create index if not exists idx_t_platform_role_status on t_platform_role (status);

create table if not exists t_platform_user_role (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    role_id bigint not null,
    created_at timestamptz not null default now(),
    created_by bigint,
    unique (user_id, role_id)
);

create index if not exists idx_t_platform_user_role_user_id on t_platform_user_role (user_id);

create index if not exists idx_t_platform_user_role_role_id on t_platform_user_role (role_id);

create table if not exists t_page_resource (
    id bigint generated by default as identity primary key,
    code varchar(100) not null,
    name varchar(100) not null,
    route_path varchar(255) not null,
    route_name varchar(100),
    component varchar(255) not null,
    permission_code varchar(150),
    keep_alive boolean not null default false,
    status varchar(32) not null default 'active',
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uk_t_page_resource_code on t_page_resource (code);

create index if not exists idx_t_page_resource_status on t_page_resource (status);

create index if not exists idx_t_page_resource_route_path on t_page_resource (route_path);

comment on table t_page_resource is '页面资源表，保存前端页面路由和页面访问资源，不代表菜单入口';
comment on column t_page_resource.id is '页面资源主键';
comment on column t_page_resource.code is '页面资源编码，全局唯一';
comment on column t_page_resource.name is '页面资源名称';
comment on column t_page_resource.route_path is '前端路由地址';
comment on column t_page_resource.route_name is '前端路由名称';
comment on column t_page_resource.component is '前端页面组件标识';
comment on column t_page_resource.permission_code is '页面访问权限编码';
comment on column t_page_resource.keep_alive is '是否缓存页面';
comment on column t_page_resource.status is '页面资源状态：active 启用，disabled 禁用';
comment on column t_page_resource.meta is '页面扩展元数据';
comment on column t_page_resource.created_at is '创建时间';
comment on column t_page_resource.updated_at is '更新时间';
comment on index uk_t_page_resource_code is '页面资源编码唯一索引';
comment on index idx_t_page_resource_status is '按页面资源状态查询';
comment on index idx_t_page_resource_route_path is '按前端路由地址查询';

create table if not exists t_permission_resource (
    id bigint generated by default as identity primary key,
    code varchar(150) not null,
    name varchar(100) not null,
    resource_type varchar(32) not null,
    page_resource_id bigint,
    http_method varchar(16),
    request_path varchar(255),
    status varchar(32) not null default 'active',
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    foreign key (page_resource_id) references t_page_resource (id)
);

create unique index if not exists uk_t_permission_resource_code on t_permission_resource (code);

create index if not exists idx_t_permission_resource_page_id on t_permission_resource (page_resource_id);

create index if not exists idx_t_permission_resource_status on t_permission_resource (status);

comment on table t_permission_resource is '操作权限资源表，保存页面按钮、接口和业务操作权限';
comment on column t_permission_resource.id is '操作权限资源主键';
comment on column t_permission_resource.code is '操作权限编码，全局唯一';
comment on column t_permission_resource.name is '操作权限名称';
comment on column t_permission_resource.resource_type is '资源类型：button 按钮，api 接口，business 业务操作';
comment on column t_permission_resource.page_resource_id is '所属页面资源主键';
comment on column t_permission_resource.http_method is '接口请求方法';
comment on column t_permission_resource.request_path is '接口请求路径';
comment on column t_permission_resource.status is '操作权限状态：active 启用，disabled 禁用';
comment on column t_permission_resource.meta is '操作权限扩展元数据';
comment on column t_permission_resource.created_at is '创建时间';
comment on column t_permission_resource.updated_at is '更新时间';
comment on index uk_t_permission_resource_code is '操作权限编码唯一索引';
comment on index idx_t_permission_resource_page_id is '按所属页面资源查询操作权限';
comment on index idx_t_permission_resource_status is '按操作权限状态查询';

create table if not exists t_system_menu (
    id bigint generated by default as identity primary key,
    parent_id bigint,
    code varchar(100) not null,
    name varchar(100) not null,
    menu_type varchar(32) not null,
    page_resource_id bigint,
    icon varchar(100),
    sort_order integer not null default 0,
    visible boolean not null default true,
    status varchar(32) not null default 'active',
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    foreign key (parent_id) references t_system_menu (id),
    foreign key (page_resource_id) references t_page_resource (id),
    check (menu_type in ('directory', 'item')),
    check ((menu_type = 'directory' and page_resource_id is null) or (menu_type = 'item' and page_resource_id is not null))
);

create unique index if not exists uk_t_system_menu_code on t_system_menu (code);

create index if not exists idx_t_system_menu_parent_sort on t_system_menu (parent_id, sort_order, id);

create index if not exists idx_t_system_menu_page_resource_id on t_system_menu (page_resource_id);

create index if not exists idx_t_system_menu_status_visible on t_system_menu (status, visible);

comment on table t_system_menu is '系统菜单表，只保存导航目录和菜单项，不保存页面按钮或接口权限';
comment on column t_system_menu.id is '系统菜单主键';
comment on column t_system_menu.parent_id is '父菜单主键，顶级菜单为空';
comment on column t_system_menu.code is '菜单编码，全局唯一';
comment on column t_system_menu.name is '菜单名称';
comment on column t_system_menu.menu_type is '菜单类型：directory 目录，item 菜单项';
comment on column t_system_menu.page_resource_id is '菜单项关联的页面资源主键，目录为空';
comment on column t_system_menu.icon is '菜单图标标识';
comment on column t_system_menu.sort_order is '同级菜单排序值，值越小越靠前';
comment on column t_system_menu.visible is '是否显示在导航菜单中';
comment on column t_system_menu.status is '菜单状态：active 启用，disabled 禁用';
comment on column t_system_menu.meta is '菜单扩展元数据';
comment on column t_system_menu.created_at is '创建时间';
comment on column t_system_menu.updated_at is '更新时间';
comment on index uk_t_system_menu_code is '菜单编码唯一索引';
comment on index idx_t_system_menu_parent_sort is '按父菜单和排序值查询菜单树';
comment on index idx_t_system_menu_page_resource_id is '按页面资源查询关联菜单';
comment on index idx_t_system_menu_status_visible is '按菜单状态和显示标记查询';

create table if not exists t_role_resource_grant (
    id bigint generated by default as identity primary key,
    role_scope varchar(32) not null,
    role_code varchar(64) not null,
    resource_type varchar(32) not null,
    resource_id bigint not null,
    effect varchar(16) not null default 'allow',
    data_scope varchar(32),
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    created_by bigint,
    check (role_scope in ('platform', 'tenant', 'organization')),
    check (resource_type in ('page', 'action')),
    check (effect in ('allow', 'deny'))
);

create unique index if not exists uk_t_role_resource_grant_resource on t_role_resource_grant (role_scope, role_code, resource_type, resource_id);

create index if not exists idx_t_role_resource_grant_role on t_role_resource_grant (role_scope, role_code, status);

create index if not exists idx_t_role_resource_grant_resource on t_role_resource_grant (resource_type, resource_id, status);

comment on table t_role_resource_grant is '角色资源授权表，保存平台、租户和组织角色对页面及操作权限的授权';
comment on column t_role_resource_grant.id is '角色资源授权主键';
comment on column t_role_resource_grant.role_scope is '角色作用域：platform 平台，tenant 租户，organization 组织';
comment on column t_role_resource_grant.role_code is '角色编码，由对应角色域校验';
comment on column t_role_resource_grant.resource_type is '资源类型：page 页面资源，action 操作权限';
comment on column t_role_resource_grant.resource_id is '页面资源或操作权限资源主键';
comment on column t_role_resource_grant.effect is '授权效果：allow 允许，deny 拒绝';
comment on column t_role_resource_grant.data_scope is '数据范围编码';
comment on column t_role_resource_grant.status is '授权状态：active 启用，disabled 禁用';
comment on column t_role_resource_grant.created_at is '创建时间';
comment on column t_role_resource_grant.created_by is '授权创建人用户主键';
comment on index uk_t_role_resource_grant_resource is '同一角色对同一资源只能配置一条授权';
comment on index idx_t_role_resource_grant_role is '按角色查询有效资源授权';
comment on index idx_t_role_resource_grant_resource is '按资源查询角色授权';

create table if not exists t_page_view_config (
    id bigint generated by default as identity primary key,
    page_resource_id bigint not null,
    role_scope varchar(32) not null,
    role_code varchar(64) not null,
    landing_path varchar(255),
    layout_code varchar(100),
    visible_components jsonb not null default '[]'::jsonb,
    hidden_components jsonb not null default '[]'::jsonb,
    action_permissions jsonb not null default '[]'::jsonb,
    config jsonb not null default '{}'::jsonb,
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    foreign key (page_resource_id) references t_page_resource (id),
    check (role_scope in ('platform', 'tenant', 'organization'))
);

create unique index if not exists uk_t_page_view_config_page_role on t_page_view_config (page_resource_id, role_scope, role_code);

create index if not exists idx_t_page_view_config_role on t_page_view_config (role_scope, role_code, status);

create index if not exists idx_t_page_view_config_page_id on t_page_view_config (page_resource_id, status);

comment on table t_page_view_config is '页面展示配置表，保存不同角色进入页面后的布局和组件展示差异';
comment on column t_page_view_config.id is '页面展示配置主键';
comment on column t_page_view_config.page_resource_id is '页面资源主键';
comment on column t_page_view_config.role_scope is '角色作用域：platform 平台，tenant 租户，organization 组织';
comment on column t_page_view_config.role_code is '角色编码，由对应角色域校验';
comment on column t_page_view_config.landing_path is '该角色进入系统后的默认页面路径';
comment on column t_page_view_config.layout_code is '页面布局编码';
comment on column t_page_view_config.visible_components is '允许展示的页面组件编码列表';
comment on column t_page_view_config.hidden_components is '需要隐藏的页面组件编码列表';
comment on column t_page_view_config.action_permissions is '页面操作权限编码列表';
comment on column t_page_view_config.config is '页面展示扩展配置';
comment on column t_page_view_config.status is '展示配置状态：active 启用，disabled 禁用';
comment on column t_page_view_config.created_at is '创建时间';
comment on column t_page_view_config.updated_at is '更新时间';
comment on index uk_t_page_view_config_page_role is '同一页面和角色只能配置一条展示配置';
comment on index idx_t_page_view_config_role is '按角色查询有效页面展示配置';
comment on index idx_t_page_view_config_page_id is '按页面资源查询有效展示配置';

create table if not exists t_tenant (
    id bigint generated by default as identity primary key,
    code varchar(64) not null,
    name varchar(255) not null,
    logo varchar(1024),
    contact_name varchar(128),
    contact_email varchar(255),
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (code)
);

create index if not exists idx_t_tenant_status on t_tenant (status);

alter table t_tenant add column if not exists description varchar(500) not null default '';

create table if not exists t_tenant_member (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    user_id bigint not null,
    role_code varchar(64) not null,
    is_primary boolean not null default false,
    status varchar(32) not null default 'active',
    joined_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tenant_id, user_id)
);

create index if not exists idx_t_tenant_member_tenant_status on t_tenant_member (tenant_id, status);

create index if not exists idx_t_tenant_member_user_id on t_tenant_member (user_id);

create index if not exists idx_t_tenant_member_tenant_role on t_tenant_member (tenant_id, role_code);

create unique index if not exists uk_t_tenant_member_active_owner on t_tenant_member (tenant_id) where role_code = 'tenant_owner' and status = 'active';

create table if not exists t_organization (
    id bigint generated by default as identity primary key,
    tenant_id bigint,
    parent_id bigint,
    code varchar(64) not null,
    name varchar(255) not null,
    leader_user_id bigint,
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tenant_id, code),
    unique (tenant_id, id),
    foreign key (tenant_id, parent_id) references t_organization (tenant_id, id)
);

create index if not exists idx_t_organization_tenant_parent on t_organization (tenant_id, parent_id);

create index if not exists idx_t_organization_tenant_status on t_organization (tenant_id, status);

alter table t_organization alter column tenant_id drop not null;

create table if not exists t_organization_member (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    user_id bigint not null,
    role_code varchar(64) not null,
    is_primary boolean not null default false,
    status varchar(32) not null default 'active',
    joined_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (organization_id, user_id)
);

create index if not exists idx_t_organization_member_organization_status on t_organization_member (organization_id, status);

create index if not exists idx_t_organization_member_user_id on t_organization_member (user_id);

create table if not exists t_knowledge_base (
    id bigint generated by default as identity primary key,
    tenant_id bigint,
    name varchar(255) not null,
    description varchar(500) not null default '',
    owner_id varchar(128) not null,
    visibility varchar(32) not null,
    embedding_model varchar(128) not null,
    chunk_size integer not null,
    chunk_overlap integer not null,
    retrieval_top_k integer not null,
    system_prompt text not null default '',
    system_prompt_version integer not null default 1,
    system_prompt_updated_at timestamptz not null default now(),
    created_by bigint not null,
    status varchar(32) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_knowledge_base_owner_id on t_knowledge_base (owner_id);

create index if not exists idx_t_knowledge_base_status on t_knowledge_base (status);

alter table t_knowledge_base add column if not exists system_prompt text not null default '';
alter table t_knowledge_base add column if not exists system_prompt_version integer not null default 1;
alter table t_knowledge_base add column if not exists system_prompt_updated_at timestamptz not null default now();
alter table t_knowledge_base add column if not exists tenant_id bigint;
alter table t_knowledge_base add column if not exists created_by bigint;

-- Existing databases must backfill tenant_id and created_by before these columns can be made mandatory.
alter table t_knowledge_base alter column tenant_id drop not null;
alter table t_knowledge_base alter column created_by set not null;

create index if not exists idx_t_knowledge_base_tenant_id on t_knowledge_base (tenant_id);

create table if not exists t_knowledge_base_organization (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    organization_id bigint not null,
    created_by bigint not null,
    created_at timestamptz not null default now(),
    unique (kb_id, organization_id)
);

create index if not exists idx_t_knowledge_base_organization_kb_id on t_knowledge_base_organization (kb_id);
create index if not exists idx_t_knowledge_base_organization_org_id on t_knowledge_base_organization (organization_id);

create table if not exists t_knowledge_base_user (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    user_id bigint not null,
    created_by bigint not null,
    created_at timestamptz not null default now(),
    unique (kb_id, user_id)
);

create index if not exists idx_t_knowledge_base_user_kb_id on t_knowledge_base_user (kb_id);
create index if not exists idx_t_knowledge_base_user_user_id on t_knowledge_base_user (user_id);

create table if not exists t_knowledge_base_prompt (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    version integer not null,
    system_prompt text not null,
    created_by varchar(128) not null,
    created_at timestamptz not null default now(),
    unique (kb_id, version)
);

create index if not exists idx_t_knowledge_base_prompt_kb_version on t_knowledge_base_prompt (kb_id, version);

create table if not exists t_document (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    source_type varchar(32) not null,
    source_name varchar(512) not null,
    source_uri text,
    content_type varchar(128) not null,
    object_path varchar(1024) not null,
    file_size bigint not null default 0,
    content_hash varchar(128) not null,
    parser varchar(128),
    status varchar(32) not null,
    error_message text,
    created_by varchar(128) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_document_kb_status on t_document (kb_id, status);

create index if not exists idx_t_document_content_hash on t_document (content_hash);

create index if not exists idx_t_document_created_by on t_document (created_by);


create table if not exists t_document_chunk (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    document_id bigint not null,
    parent_id bigint,
    chunk_index integer not null,
    content text not null,
    content_hash varchar(128) not null,
    source_name varchar(512) not null,
    page integer,
    section varchar(512),
    start_index integer,
    token_count integer,
    metadata jsonb not null default '{}'::jsonb,
    embedding_model varchar(128) not null,
    embedding vector,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_document_chunk_kb_doc on t_document_chunk (kb_id, document_id);

create index if not exists idx_t_document_chunk_kb_index on t_document_chunk (kb_id, chunk_index);

create index if not exists idx_t_document_chunk_content_hash on t_document_chunk (content_hash);

create index if not exists idx_t_document_chunk_metadata_gin on t_document_chunk using gin (metadata);

-- Create the vector index after the embedding dimension and distance metric are finalized.
-- Example for cosine distance with HNSW:
-- create index if not exists idx_t_document_chunk_embedding_hnsw on t_document_chunk using hnsw (embedding vector_cosine_ops);


create table if not exists t_indexing_task (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    kb_id bigint not null,
    task_type varchar(32) not null,
    status varchar(32) not null,
    attempts integer not null default 0,
    max_attempts integer not null default 3,
    error_message text,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_indexing_task_document_id on t_indexing_task (document_id);

create index if not exists idx_t_indexing_task_status on t_indexing_task (status);

create index if not exists idx_t_indexing_task_kb_status on t_indexing_task (kb_id, status);


create table if not exists t_conversation (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    user_id varchar(128) not null,
    title varchar(255),
    status varchar(32) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_t_conversation_user_id on t_conversation (user_id);

create index if not exists idx_t_conversation_kb_user on t_conversation (kb_id, user_id);


create table if not exists t_conversation_message (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    kb_id bigint not null,
    user_id varchar(128) not null,
    role varchar(32) not null,
    content text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_conversation_message_conversation_id on t_conversation_message (conversation_id);

create index if not exists idx_t_conversation_message_kb_user on t_conversation_message (kb_id, user_id);

create index if not exists idx_t_conversation_message_created_at on t_conversation_message (created_at);


create table if not exists t_message_citation (
    id bigint generated by default as identity primary key,
    message_id bigint not null,
    kb_id bigint not null,
    document_id bigint not null,
    chunk_id bigint not null,
    source_name varchar(512) not null,
    page integer,
    snippet text not null,
    score numeric(8, 6),
    rank integer not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_message_citation_message_id on t_message_citation (message_id);

create index if not exists idx_t_message_citation_document_id on t_message_citation (document_id);

create index if not exists idx_t_message_citation_chunk_id on t_message_citation (chunk_id);


create table if not exists t_evaluation_feedback (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    conversation_id bigint,
    message_id bigint,
    question text not null,
    expected_answer text,
    actual_answer text,
    expected_sources jsonb not null default '[]'::jsonb,
    rating integer,
    labels jsonb not null default '[]'::jsonb,
    comment text,
    created_by varchar(128) not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_evaluation_feedback_kb_created on t_evaluation_feedback (kb_id, created_at);

create index if not exists idx_t_evaluation_feedback_message_id on t_evaluation_feedback (message_id);


create table if not exists t_audit_log (
    id bigint generated by default as identity primary key,
    actor_id varchar(128) not null,
    action varchar(128) not null,
    action_cn varchar(128) not null,
    target_type varchar(64) not null,
    target_id varchar(128),
    request_id varchar(128),
    request_summary jsonb not null default '{}'::jsonb,
    result varchar(32) not null,
    error_message text,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_audit_log_actor_id on t_audit_log (actor_id);

create index if not exists idx_t_audit_log_target on t_audit_log (target_type, target_id);

create index if not exists idx_t_audit_log_created_at on t_audit_log (created_at);
