begin;

create table if not exists t_system_menu_action (
    id bigint generated by default as identity primary key,
    menu_id bigint not null,
    code varchar(128) not null,
    name varchar(100) not null,
    action_type varchar(32) not null default 'business',
    sort_order integer not null default 0,
    status varchar(32) not null default 'active',
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (action_type in ('button', 'business'))
);

create unique index if not exists uk_t_system_menu_action_code on t_system_menu_action (code);
create unique index if not exists uk_t_system_menu_action_menu_name on t_system_menu_action (menu_id, name);
create index if not exists idx_t_system_menu_action_menu on t_system_menu_action (menu_id, status);

create table if not exists t_role_menu_action (
    id bigint generated by default as identity primary key,
    role_scope varchar(32) not null,
    role_code varchar(64) not null,
    action_id bigint not null,
    status varchar(32) not null default 'active',
    created_at timestamptz not null default now(),
    created_by bigint,
    updated_at timestamptz not null default now(),
    check (role_scope in ('platform', 'tenant', 'organization'))
);

create unique index if not exists uk_t_role_menu_action_role_action on t_role_menu_action (role_scope, role_code, action_id);
create index if not exists idx_t_role_menu_action_role on t_role_menu_action (role_scope, role_code, status);
create index if not exists idx_t_role_menu_action_action on t_role_menu_action (action_id, status);

commit;
