begin;

create table if not exists t_knowledge_base_qa_config_version (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    version_no integer not null,
    status varchar(20) not null,
    config_json jsonb not null default '{}'::jsonb,
    change_summary_json jsonb not null default '{}'::jsonb,
    requires_reindex boolean not null default false,
    affected_document_count integer not null default 0,
    created_by bigint not null,
    published_by bigint,
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (kb_id, version_no)
);

create unique index if not exists uq_t_knowledge_base_qa_config_draft on t_knowledge_base_qa_config_version (kb_id) where status = 'draft';
create unique index if not exists uq_t_knowledge_base_qa_config_published on t_knowledge_base_qa_config_version (kb_id) where status = 'published';
create index if not exists idx_t_knowledge_base_qa_config_kb_status on t_knowledge_base_qa_config_version (kb_id, status);

create table if not exists t_knowledge_base_qa_config_audit (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    config_version_id bigint,
    action varchar(32) not null,
    actor_id bigint not null,
    before_json jsonb not null default '{}'::jsonb,
    after_json jsonb not null default '{}'::jsonb,
    result varchar(20) not null,
    error_message text,
    created_at timestamptz not null default now()
);

create index if not exists idx_t_knowledge_base_qa_config_audit_kb_created on t_knowledge_base_qa_config_audit (kb_id, created_at);

create table if not exists t_knowledge_base_index_version (
    id bigint generated by default as identity primary key,
    kb_id bigint not null,
    generation varchar(64) not null,
    config_version_id bigint,
    status varchar(20) not null,
    vector_collection varchar(255) not null,
    created_at timestamptz not null default now(),
    activated_at timestamptz,
    retired_at timestamptz,
    unique (kb_id, generation)
);

create unique index if not exists uq_t_knowledge_base_index_active on t_knowledge_base_index_version (kb_id) where status = 'active';
create index if not exists idx_t_knowledge_base_index_kb_status on t_knowledge_base_index_version (kb_id, status);

alter table t_knowledge_base add column if not exists active_index_version_id bigint;
alter table t_document_chunk add column if not exists index_version_id bigint;
alter table t_indexing_task add column if not exists config_version_id bigint;
alter table t_indexing_task add column if not exists index_version_id bigint;
alter table t_conversation add column if not exists qa_config_version_id bigint;
alter table t_conversation add column if not exists index_version_id bigint;
alter table t_conversation_message add column if not exists qa_config_version_id bigint;
alter table t_conversation_message add column if not exists index_version_id bigint;

create index if not exists idx_t_document_chunk_kb_index_version on t_document_chunk (kb_id, index_version_id);
create index if not exists idx_t_indexing_task_kb_index_version on t_indexing_task (kb_id, index_version_id);
create index if not exists idx_t_conversation_index_version on t_conversation (kb_id, index_version_id);
create index if not exists idx_t_conversation_message_index_version on t_conversation_message (kb_id, index_version_id);

insert into t_knowledge_base_index_version (
    kb_id,
    generation,
    config_version_id,
    status,
    vector_collection,
    activated_at
)
select
    kb.id,
    'generation-001',
    published.id,
    'active',
    'kb_' || kb.id::text || '_generation_001',
    now()
from t_knowledge_base kb
left join t_knowledge_base_qa_config_version published
    on published.kb_id = kb.id and published.status = 'published'
where not exists (
    select 1
    from t_knowledge_base_index_version existing
    where existing.kb_id = kb.id
);

update t_knowledge_base kb
set active_index_version_id = index_version.id
from t_knowledge_base_index_version index_version
where index_version.kb_id = kb.id
  and index_version.status = 'active'
  and kb.active_index_version_id is null;

update t_document_chunk chunk
set index_version_id = kb.active_index_version_id
from t_knowledge_base kb
where kb.id = chunk.kb_id
  and chunk.index_version_id is null;

update t_conversation conversation
set index_version_id = kb.active_index_version_id
from t_knowledge_base kb
where kb.id = conversation.kb_id
  and conversation.index_version_id is null;

update t_conversation conversation
set qa_config_version_id = index_version.config_version_id
from t_knowledge_base_index_version index_version
where index_version.id = conversation.index_version_id
  and conversation.qa_config_version_id is null;

update t_conversation_message message
set index_version_id = conversation.index_version_id,
    qa_config_version_id = conversation.qa_config_version_id
from t_conversation conversation
where conversation.id = message.conversation_id
  and message.index_version_id is null;

update t_indexing_task task
set index_version_id = kb.active_index_version_id
from t_knowledge_base kb
where kb.id = task.kb_id
  and task.index_version_id is null;

update t_indexing_task task
set config_version_id = index_version.config_version_id
from t_knowledge_base_index_version index_version
where index_version.id = task.index_version_id
  and task.config_version_id is null;

commit;
