import pytest
from pydantic import ValidationError

from app.db.models import metadata
from app.schemas.monitoring import (
    AnalysisConversationModifyRequest,
    AnalysisConversationRequest,
    MetricRuleRequest,
)


def test_monitoring_ddl_contains_all_tables_without_business_constraints():
    ddl = open("scripts/db/data_table_ddl.sql", encoding="utf-8").read()
    monitoring_ddl = ddl[ddl.index("create table if not exists t_monitor_event") :]
    assert monitoring_ddl.count("create table if not exists t_monitor_") == 13
    assert "check (" not in monitoring_ddl.lower()
    assert "generated by default as identity primary key" in monitoring_ddl


def test_monitoring_tables_have_identity_primary_keys():
    names = [name for name in metadata.tables if name.startswith("t_monitor_")]
    assert len(names) == 13
    for name in names:
        table = metadata.tables[name]
        assert table.c.id.primary_key
        assert table.c.id.identity is not None


def test_analysis_conversation_uses_monitoring_scope_without_kb_id():
    payload = AnalysisConversationRequest(title="趋势分析", scope_key="platform")
    assert payload.context == {}
    assert MetricRuleRequest(metric_code="p95").window_seconds == 300


def test_analysis_conversation_modify_title_length_boundary():
    assert AnalysisConversationModifyRequest(title="会话名称").title == "会话名称"
    with pytest.raises(ValidationError):
        AnalysisConversationModifyRequest(title="")
    with pytest.raises(ValidationError):
        AnalysisConversationModifyRequest(title="会" * 256)
